/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as ProspeccaoRouteImport } from './routes/prospeccao'
import { Route as PropostasRouteImport } from './routes/propostas'
import { Route as MetasObjetivosRouteImport } from './routes/metas-objetivos'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KickoffRouteImport } from './routes/kickoff'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CadenciaRouteImport } from './routes/cadencia'
import { Route as BriefingsRouteImport } from './routes/briefings'
import { Route as BiRouteImport } from './routes/bi'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperacoesIndexRouteImport } from './routes/operacoes.index'
import { Route as PropostasIdRouteImport } from './routes/propostas.$id'
import { Route as PropostaTokenRouteImport } from './routes/proposta.$token'
import { Route as OperacoesTrafegoRouteImport } from './routes/operacoes.trafego'
import { Route as OperacoesRenovacoesRouteImport } from './routes/operacoes.renovacoes'
import { Route as OperacoesRelatoriosRouteImport } from './routes/operacoes.relatorios'
import { Route as OperacoesRelacionamentoRouteImport } from './routes/operacoes.relacionamento'
import { Route as OperacoesOnboardingRouteImport } from './routes/operacoes.onboarding'
import { Route as OperacoesKanbanRouteImport } from './routes/operacoes.kanban'
import { Route as OperacoesImplantacaoRouteImport } from './routes/operacoes.implantacao'
import { Route as OperacoesFinanceiroRouteImport } from './routes/operacoes.financeiro'
import { Route as OperacoesDashboardRouteImport } from './routes/operacoes.dashboard'
import { Route as OperacoesCredenciaisRouteImport } from './routes/operacoes.credenciais'
import { Route as OperacoesClientesRouteImport } from './routes/operacoes.clientes'
import { Route as OperacoesCampanhasRouteImport } from './routes/operacoes.campanhas'
import { Route as OperacoesAgendaRouteImport } from './routes/operacoes.agenda'
import { Route as ContratosIdRouteImport } from './routes/contratos.$id'
import { Route as CatalogoNovoRouteImport } from './routes/catalogo.novo'
import { Route as CatalogoIdRouteImport } from './routes/catalogo.$id'
import { Route as BriefingsIdRouteImport } from './routes/briefings.$id'
import { Route as BriefingTokenRouteImport } from './routes/briefing.$token'
import { Route as OperacoesClientesIdRouteImport } from './routes/operacoes.clientes.$id'
import { Route as OperacoesClientesIdIndexRouteImport } from './routes/operacoes.clientes.$id.index'
import { Route as OperacoesClientesIdOperacoesRouteImport } from './routes/operacoes.clientes.$id.operacoes'
import { Route as OperacoesClientesIdHistoricoRouteImport } from './routes/operacoes.clientes.$id.historico'
import { Route as OperacoesClientesIdFinanceiroRouteImport } from './routes/operacoes.clientes.$id.financeiro'
import { Route as OperacoesClientesIdDocumentosRouteImport } from './routes/operacoes.clientes.$id.documentos'
import { Route as OperacoesClientesIdComercialRouteImport } from './routes/operacoes.clientes.$id.comercial'

const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspeccaoRoute = ProspeccaoRouteImport.update({
  id: '/prospeccao',
  path: '/prospeccao',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasRoute = PropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasObjetivosRoute = MetasObjetivosRouteImport.update({
  id: '/metas-objetivos',
  path: '/metas-objetivos',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KickoffRoute = KickoffRouteImport.update({
  id: '/kickoff',
  path: '/kickoff',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CadenciaRoute = CadenciaRouteImport.update({
  id: '/cadencia',
  path: '/cadencia',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingsRoute = BriefingsRouteImport.update({
  id: '/briefings',
  path: '/briefings',
  getParentRoute: () => rootRouteImport,
} as any)
const BiRoute = BiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesIndexRoute = OperacoesIndexRouteImport.update({
  id: '/operacoes/',
  path: '/operacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasIdRoute = PropostasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropostasRoute,
} as any)
const PropostaTokenRoute = PropostaTokenRouteImport.update({
  id: '/proposta/$token',
  path: '/proposta/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesTrafegoRoute = OperacoesTrafegoRouteImport.update({
  id: '/operacoes/trafego',
  path: '/operacoes/trafego',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesRenovacoesRoute = OperacoesRenovacoesRouteImport.update({
  id: '/operacoes/renovacoes',
  path: '/operacoes/renovacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesRelatoriosRoute = OperacoesRelatoriosRouteImport.update({
  id: '/operacoes/relatorios',
  path: '/operacoes/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesRelacionamentoRoute = OperacoesRelacionamentoRouteImport.update({
  id: '/operacoes/relacionamento',
  path: '/operacoes/relacionamento',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesOnboardingRoute = OperacoesOnboardingRouteImport.update({
  id: '/operacoes/onboarding',
  path: '/operacoes/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesKanbanRoute = OperacoesKanbanRouteImport.update({
  id: '/operacoes/kanban',
  path: '/operacoes/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesImplantacaoRoute = OperacoesImplantacaoRouteImport.update({
  id: '/operacoes/implantacao',
  path: '/operacoes/implantacao',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesFinanceiroRoute = OperacoesFinanceiroRouteImport.update({
  id: '/operacoes/financeiro',
  path: '/operacoes/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesDashboardRoute = OperacoesDashboardRouteImport.update({
  id: '/operacoes/dashboard',
  path: '/operacoes/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesCredenciaisRoute = OperacoesCredenciaisRouteImport.update({
  id: '/operacoes/credenciais',
  path: '/operacoes/credenciais',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesClientesRoute = OperacoesClientesRouteImport.update({
  id: '/operacoes/clientes',
  path: '/operacoes/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesCampanhasRoute = OperacoesCampanhasRouteImport.update({
  id: '/operacoes/campanhas',
  path: '/operacoes/campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesAgendaRoute = OperacoesAgendaRouteImport.update({
  id: '/operacoes/agenda',
  path: '/operacoes/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosIdRoute = ContratosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ContratosRoute,
} as any)
const CatalogoNovoRoute = CatalogoNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => CatalogoRoute,
} as any)
const CatalogoIdRoute = CatalogoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CatalogoRoute,
} as any)
const BriefingsIdRoute = BriefingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BriefingsRoute,
} as any)
const BriefingTokenRoute = BriefingTokenRouteImport.update({
  id: '/briefing/$token',
  path: '/briefing/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesClientesIdRoute = OperacoesClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OperacoesClientesRoute,
} as any)
const OperacoesClientesIdIndexRoute =
  OperacoesClientesIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OperacoesClientesIdRoute,
  } as any)
const OperacoesClientesIdOperacoesRoute =
  OperacoesClientesIdOperacoesRouteImport.update({
    id: '/operacoes',
    path: '/operacoes',
    getParentRoute: () => OperacoesClientesIdRoute,
  } as any)
const OperacoesClientesIdHistoricoRoute =
  OperacoesClientesIdHistoricoRouteImport.update({
    id: '/historico',
    path: '/historico',
    getParentRoute: () => OperacoesClientesIdRoute,
  } as any)
const OperacoesClientesIdFinanceiroRoute =
  OperacoesClientesIdFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => OperacoesClientesIdRoute,
  } as any)
const OperacoesClientesIdDocumentosRoute =
  OperacoesClientesIdDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => OperacoesClientesIdRoute,
  } as any)
const OperacoesClientesIdComercialRoute =
  OperacoesClientesIdComercialRouteImport.update({
    id: '/comercial',
    path: '/comercial',
    getParentRoute: () => OperacoesClientesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bi': typeof BiRoute
  '/briefings': typeof BriefingsRouteWithChildren
  '/cadencia': typeof CadenciaRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/contratos': typeof ContratosRouteWithChildren
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/kickoff': typeof KickoffRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/metas-objetivos': typeof MetasObjetivosRoute
  '/propostas': typeof PropostasRouteWithChildren
  '/prospeccao': typeof ProspeccaoRoute
  '/tarefas': typeof TarefasRoute
  '/briefing/$token': typeof BriefingTokenRoute
  '/briefings/$id': typeof BriefingsIdRoute
  '/catalogo/$id': typeof CatalogoIdRoute
  '/catalogo/novo': typeof CatalogoNovoRoute
  '/contratos/$id': typeof ContratosIdRoute
  '/operacoes/agenda': typeof OperacoesAgendaRoute
  '/operacoes/campanhas': typeof OperacoesCampanhasRoute
  '/operacoes/clientes': typeof OperacoesClientesRouteWithChildren
  '/operacoes/credenciais': typeof OperacoesCredenciaisRoute
  '/operacoes/dashboard': typeof OperacoesDashboardRoute
  '/operacoes/financeiro': typeof OperacoesFinanceiroRoute
  '/operacoes/implantacao': typeof OperacoesImplantacaoRoute
  '/operacoes/kanban': typeof OperacoesKanbanRoute
  '/operacoes/onboarding': typeof OperacoesOnboardingRoute
  '/operacoes/relacionamento': typeof OperacoesRelacionamentoRoute
  '/operacoes/relatorios': typeof OperacoesRelatoriosRoute
  '/operacoes/renovacoes': typeof OperacoesRenovacoesRoute
  '/operacoes/trafego': typeof OperacoesTrafegoRoute
  '/proposta/$token': typeof PropostaTokenRoute
  '/propostas/$id': typeof PropostasIdRoute
  '/operacoes/': typeof OperacoesIndexRoute
  '/operacoes/clientes/$id': typeof OperacoesClientesIdRouteWithChildren
  '/operacoes/clientes/$id/comercial': typeof OperacoesClientesIdComercialRoute
  '/operacoes/clientes/$id/documentos': typeof OperacoesClientesIdDocumentosRoute
  '/operacoes/clientes/$id/financeiro': typeof OperacoesClientesIdFinanceiroRoute
  '/operacoes/clientes/$id/historico': typeof OperacoesClientesIdHistoricoRoute
  '/operacoes/clientes/$id/operacoes': typeof OperacoesClientesIdOperacoesRoute
  '/operacoes/clientes/$id/': typeof OperacoesClientesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bi': typeof BiRoute
  '/briefings': typeof BriefingsRouteWithChildren
  '/cadencia': typeof CadenciaRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/contratos': typeof ContratosRouteWithChildren
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/kickoff': typeof KickoffRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/metas-objetivos': typeof MetasObjetivosRoute
  '/propostas': typeof PropostasRouteWithChildren
  '/prospeccao': typeof ProspeccaoRoute
  '/tarefas': typeof TarefasRoute
  '/briefing/$token': typeof BriefingTokenRoute
  '/briefings/$id': typeof BriefingsIdRoute
  '/catalogo/$id': typeof CatalogoIdRoute
  '/catalogo/novo': typeof CatalogoNovoRoute
  '/contratos/$id': typeof ContratosIdRoute
  '/operacoes/agenda': typeof OperacoesAgendaRoute
  '/operacoes/campanhas': typeof OperacoesCampanhasRoute
  '/operacoes/clientes': typeof OperacoesClientesRouteWithChildren
  '/operacoes/credenciais': typeof OperacoesCredenciaisRoute
  '/operacoes/dashboard': typeof OperacoesDashboardRoute
  '/operacoes/financeiro': typeof OperacoesFinanceiroRoute
  '/operacoes/implantacao': typeof OperacoesImplantacaoRoute
  '/operacoes/kanban': typeof OperacoesKanbanRoute
  '/operacoes/onboarding': typeof OperacoesOnboardingRoute
  '/operacoes/relacionamento': typeof OperacoesRelacionamentoRoute
  '/operacoes/relatorios': typeof OperacoesRelatoriosRoute
  '/operacoes/renovacoes': typeof OperacoesRenovacoesRoute
  '/operacoes/trafego': typeof OperacoesTrafegoRoute
  '/proposta/$token': typeof PropostaTokenRoute
  '/propostas/$id': typeof PropostasIdRoute
  '/operacoes': typeof OperacoesIndexRoute
  '/operacoes/clientes/$id/comercial': typeof OperacoesClientesIdComercialRoute
  '/operacoes/clientes/$id/documentos': typeof OperacoesClientesIdDocumentosRoute
  '/operacoes/clientes/$id/financeiro': typeof OperacoesClientesIdFinanceiroRoute
  '/operacoes/clientes/$id/historico': typeof OperacoesClientesIdHistoricoRoute
  '/operacoes/clientes/$id/operacoes': typeof OperacoesClientesIdOperacoesRoute
  '/operacoes/clientes/$id': typeof OperacoesClientesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bi': typeof BiRoute
  '/briefings': typeof BriefingsRouteWithChildren
  '/cadencia': typeof CadenciaRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/contratos': typeof ContratosRouteWithChildren
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/kickoff': typeof KickoffRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/metas-objetivos': typeof MetasObjetivosRoute
  '/propostas': typeof PropostasRouteWithChildren
  '/prospeccao': typeof ProspeccaoRoute
  '/tarefas': typeof TarefasRoute
  '/briefing/$token': typeof BriefingTokenRoute
  '/briefings/$id': typeof BriefingsIdRoute
  '/catalogo/$id': typeof CatalogoIdRoute
  '/catalogo/novo': typeof CatalogoNovoRoute
  '/contratos/$id': typeof ContratosIdRoute
  '/operacoes/agenda': typeof OperacoesAgendaRoute
  '/operacoes/campanhas': typeof OperacoesCampanhasRoute
  '/operacoes/clientes': typeof OperacoesClientesRouteWithChildren
  '/operacoes/credenciais': typeof OperacoesCredenciaisRoute
  '/operacoes/dashboard': typeof OperacoesDashboardRoute
  '/operacoes/financeiro': typeof OperacoesFinanceiroRoute
  '/operacoes/implantacao': typeof OperacoesImplantacaoRoute
  '/operacoes/kanban': typeof OperacoesKanbanRoute
  '/operacoes/onboarding': typeof OperacoesOnboardingRoute
  '/operacoes/relacionamento': typeof OperacoesRelacionamentoRoute
  '/operacoes/relatorios': typeof OperacoesRelatoriosRoute
  '/operacoes/renovacoes': typeof OperacoesRenovacoesRoute
  '/operacoes/trafego': typeof OperacoesTrafegoRoute
  '/proposta/$token': typeof PropostaTokenRoute
  '/propostas/$id': typeof PropostasIdRoute
  '/operacoes/': typeof OperacoesIndexRoute
  '/operacoes/clientes/$id': typeof OperacoesClientesIdRouteWithChildren
  '/operacoes/clientes/$id/comercial': typeof OperacoesClientesIdComercialRoute
  '/operacoes/clientes/$id/documentos': typeof OperacoesClientesIdDocumentosRoute
  '/operacoes/clientes/$id/financeiro': typeof OperacoesClientesIdFinanceiroRoute
  '/operacoes/clientes/$id/historico': typeof OperacoesClientesIdHistoricoRoute
  '/operacoes/clientes/$id/operacoes': typeof OperacoesClientesIdOperacoesRoute
  '/operacoes/clientes/$id/': typeof OperacoesClientesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bi'
    | '/briefings'
    | '/cadencia'
    | '/catalogo'
    | '/contratos'
    | '/crm'
    | '/dashboard'
    | '/kickoff'
    | '/login'
    | '/metas'
    | '/metas-objetivos'
    | '/propostas'
    | '/prospeccao'
    | '/tarefas'
    | '/briefing/$token'
    | '/briefings/$id'
    | '/catalogo/$id'
    | '/catalogo/novo'
    | '/contratos/$id'
    | '/operacoes/agenda'
    | '/operacoes/campanhas'
    | '/operacoes/clientes'
    | '/operacoes/credenciais'
    | '/operacoes/dashboard'
    | '/operacoes/financeiro'
    | '/operacoes/implantacao'
    | '/operacoes/kanban'
    | '/operacoes/onboarding'
    | '/operacoes/relacionamento'
    | '/operacoes/relatorios'
    | '/operacoes/renovacoes'
    | '/operacoes/trafego'
    | '/proposta/$token'
    | '/propostas/$id'
    | '/operacoes/'
    | '/operacoes/clientes/$id'
    | '/operacoes/clientes/$id/comercial'
    | '/operacoes/clientes/$id/documentos'
    | '/operacoes/clientes/$id/financeiro'
    | '/operacoes/clientes/$id/historico'
    | '/operacoes/clientes/$id/operacoes'
    | '/operacoes/clientes/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bi'
    | '/briefings'
    | '/cadencia'
    | '/catalogo'
    | '/contratos'
    | '/crm'
    | '/dashboard'
    | '/kickoff'
    | '/login'
    | '/metas'
    | '/metas-objetivos'
    | '/propostas'
    | '/prospeccao'
    | '/tarefas'
    | '/briefing/$token'
    | '/briefings/$id'
    | '/catalogo/$id'
    | '/catalogo/novo'
    | '/contratos/$id'
    | '/operacoes/agenda'
    | '/operacoes/campanhas'
    | '/operacoes/clientes'
    | '/operacoes/credenciais'
    | '/operacoes/dashboard'
    | '/operacoes/financeiro'
    | '/operacoes/implantacao'
    | '/operacoes/kanban'
    | '/operacoes/onboarding'
    | '/operacoes/relacionamento'
    | '/operacoes/relatorios'
    | '/operacoes/renovacoes'
    | '/operacoes/trafego'
    | '/proposta/$token'
    | '/propostas/$id'
    | '/operacoes'
    | '/operacoes/clientes/$id/comercial'
    | '/operacoes/clientes/$id/documentos'
    | '/operacoes/clientes/$id/financeiro'
    | '/operacoes/clientes/$id/historico'
    | '/operacoes/clientes/$id/operacoes'
    | '/operacoes/clientes/$id'
  id:
    | '__root__'
    | '/'
    | '/bi'
    | '/briefings'
    | '/cadencia'
    | '/catalogo'
    | '/contratos'
    | '/crm'
    | '/dashboard'
    | '/kickoff'
    | '/login'
    | '/metas'
    | '/metas-objetivos'
    | '/propostas'
    | '/prospeccao'
    | '/tarefas'
    | '/briefing/$token'
    | '/briefings/$id'
    | '/catalogo/$id'
    | '/catalogo/novo'
    | '/contratos/$id'
    | '/operacoes/agenda'
    | '/operacoes/campanhas'
    | '/operacoes/clientes'
    | '/operacoes/credenciais'
    | '/operacoes/dashboard'
    | '/operacoes/financeiro'
    | '/operacoes/implantacao'
    | '/operacoes/kanban'
    | '/operacoes/onboarding'
    | '/operacoes/relacionamento'
    | '/operacoes/relatorios'
    | '/operacoes/renovacoes'
    | '/operacoes/trafego'
    | '/proposta/$token'
    | '/propostas/$id'
    | '/operacoes/'
    | '/operacoes/clientes/$id'
    | '/operacoes/clientes/$id/comercial'
    | '/operacoes/clientes/$id/documentos'
    | '/operacoes/clientes/$id/financeiro'
    | '/operacoes/clientes/$id/historico'
    | '/operacoes/clientes/$id/operacoes'
    | '/operacoes/clientes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiRoute: typeof BiRoute
  BriefingsRoute: typeof BriefingsRouteWithChildren
  CadenciaRoute: typeof CadenciaRoute
  CatalogoRoute: typeof CatalogoRouteWithChildren
  ContratosRoute: typeof ContratosRouteWithChildren
  CrmRoute: typeof CrmRoute
  DashboardRoute: typeof DashboardRoute
  KickoffRoute: typeof KickoffRoute
  LoginRoute: typeof LoginRoute
  MetasRoute: typeof MetasRoute
  MetasObjetivosRoute: typeof MetasObjetivosRoute
  PropostasRoute: typeof PropostasRouteWithChildren
  ProspeccaoRoute: typeof ProspeccaoRoute
  TarefasRoute: typeof TarefasRoute
  BriefingTokenRoute: typeof BriefingTokenRoute
  OperacoesAgendaRoute: typeof OperacoesAgendaRoute
  OperacoesCampanhasRoute: typeof OperacoesCampanhasRoute
  OperacoesClientesRoute: typeof OperacoesClientesRouteWithChildren
  OperacoesCredenciaisRoute: typeof OperacoesCredenciaisRoute
  OperacoesDashboardRoute: typeof OperacoesDashboardRoute
  OperacoesFinanceiroRoute: typeof OperacoesFinanceiroRoute
  OperacoesImplantacaoRoute: typeof OperacoesImplantacaoRoute
  OperacoesKanbanRoute: typeof OperacoesKanbanRoute
  OperacoesOnboardingRoute: typeof OperacoesOnboardingRoute
  OperacoesRelacionamentoRoute: typeof OperacoesRelacionamentoRoute
  OperacoesRelatoriosRoute: typeof OperacoesRelatoriosRoute
  OperacoesRenovacoesRoute: typeof OperacoesRenovacoesRoute
  OperacoesTrafegoRoute: typeof OperacoesTrafegoRoute
  PropostaTokenRoute: typeof PropostaTokenRoute
  OperacoesIndexRoute: typeof OperacoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospeccao': {
      id: '/prospeccao'
      path: '/prospeccao'
      fullPath: '/prospeccao'
      preLoaderRoute: typeof ProspeccaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas': {
      id: '/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof PropostasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas-objetivos': {
      id: '/metas-objetivos'
      path: '/metas-objetivos'
      fullPath: '/metas-objetivos'
      preLoaderRoute: typeof MetasObjetivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kickoff': {
      id: '/kickoff'
      path: '/kickoff'
      fullPath: '/kickoff'
      preLoaderRoute: typeof KickoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadencia': {
      id: '/cadencia'
      path: '/cadencia'
      fullPath: '/cadencia'
      preLoaderRoute: typeof CadenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefings': {
      id: '/briefings'
      path: '/briefings'
      fullPath: '/briefings'
      preLoaderRoute: typeof BriefingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bi': {
      id: '/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof BiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes/': {
      id: '/operacoes/'
      path: '/operacoes'
      fullPath: '/operacoes/'
      preLoaderRoute: typeof OperacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas/$id': {
      id: '/propostas/$id'
      path: '/$id'
      fullPath: '/propostas/$id'
      preLoaderRoute: typeof PropostasIdRouteImport
      parentRoute: typeof PropostasRoute
    }
    '/proposta/$token': {
      id: '/proposta/$token'
      path: '/proposta/$token'
      fullPath: '/proposta/$token'
      preLoaderRoute: typeof PropostaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes/trafego': {
      id: '/operacoes/trafego'
      path: '/operacoes/trafego'
      fullPath: '/operacoes/trafego'
      preLoaderRoute: typeof OperacoesTrafegoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes/renovacoes': {
      id: '/operacoes/renovacoes'
      path: '/operacoes/renovacoes'
      fullPath: '/operacoes/renovacoes'
      preLoaderRoute: typeof OperacoesRenovacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes/relatorios': {
      id: '/operacoes/relatorios'
      path: '/operacoes/relatorios'
      fullPath: '/operacoes/relatorios'
      preLoaderRoute: typeof OperacoesRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes/relacionamento': {
      id: '/operacoes/relacionamento'
      path: '/operacoes/relacionamento'
      fullPath: '/operacoes/relacionamento'
      preLoaderRoute: typeof OperacoesRelacionamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes/onboarding': {
      id: '/operacoes/onboarding'
      path: '/operacoes/onboarding'
      fullPath: '/operacoes/onboarding'
      preLoaderRoute: typeof OperacoesOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes/kanban': {
      id: '/operacoes/kanban'
      path: '/operacoes/kanban'
      fullPath: '/operacoes/kanban'
      preLoaderRoute: typeof OperacoesKanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes/implantacao': {
      id: '/operacoes/implantacao'
      path: '/operacoes/implantacao'
      fullPath: '/operacoes/implantacao'
      preLoaderRoute: typeof OperacoesImplantacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes/financeiro': {
      id: '/operacoes/financeiro'
      path: '/operacoes/financeiro'
      fullPath: '/operacoes/financeiro'
      preLoaderRoute: typeof OperacoesFinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes/dashboard': {
      id: '/operacoes/dashboard'
      path: '/operacoes/dashboard'
      fullPath: '/operacoes/dashboard'
      preLoaderRoute: typeof OperacoesDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes/credenciais': {
      id: '/operacoes/credenciais'
      path: '/operacoes/credenciais'
      fullPath: '/operacoes/credenciais'
      preLoaderRoute: typeof OperacoesCredenciaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes/clientes': {
      id: '/operacoes/clientes'
      path: '/operacoes/clientes'
      fullPath: '/operacoes/clientes'
      preLoaderRoute: typeof OperacoesClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes/campanhas': {
      id: '/operacoes/campanhas'
      path: '/operacoes/campanhas'
      fullPath: '/operacoes/campanhas'
      preLoaderRoute: typeof OperacoesCampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes/agenda': {
      id: '/operacoes/agenda'
      path: '/operacoes/agenda'
      fullPath: '/operacoes/agenda'
      preLoaderRoute: typeof OperacoesAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos/$id': {
      id: '/contratos/$id'
      path: '/$id'
      fullPath: '/contratos/$id'
      preLoaderRoute: typeof ContratosIdRouteImport
      parentRoute: typeof ContratosRoute
    }
    '/catalogo/novo': {
      id: '/catalogo/novo'
      path: '/novo'
      fullPath: '/catalogo/novo'
      preLoaderRoute: typeof CatalogoNovoRouteImport
      parentRoute: typeof CatalogoRoute
    }
    '/catalogo/$id': {
      id: '/catalogo/$id'
      path: '/$id'
      fullPath: '/catalogo/$id'
      preLoaderRoute: typeof CatalogoIdRouteImport
      parentRoute: typeof CatalogoRoute
    }
    '/briefings/$id': {
      id: '/briefings/$id'
      path: '/$id'
      fullPath: '/briefings/$id'
      preLoaderRoute: typeof BriefingsIdRouteImport
      parentRoute: typeof BriefingsRoute
    }
    '/briefing/$token': {
      id: '/briefing/$token'
      path: '/briefing/$token'
      fullPath: '/briefing/$token'
      preLoaderRoute: typeof BriefingTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes/clientes/$id': {
      id: '/operacoes/clientes/$id'
      path: '/$id'
      fullPath: '/operacoes/clientes/$id'
      preLoaderRoute: typeof OperacoesClientesIdRouteImport
      parentRoute: typeof OperacoesClientesRoute
    }
    '/operacoes/clientes/$id/': {
      id: '/operacoes/clientes/$id/'
      path: '/'
      fullPath: '/operacoes/clientes/$id/'
      preLoaderRoute: typeof OperacoesClientesIdIndexRouteImport
      parentRoute: typeof OperacoesClientesIdRoute
    }
    '/operacoes/clientes/$id/operacoes': {
      id: '/operacoes/clientes/$id/operacoes'
      path: '/operacoes'
      fullPath: '/operacoes/clientes/$id/operacoes'
      preLoaderRoute: typeof OperacoesClientesIdOperacoesRouteImport
      parentRoute: typeof OperacoesClientesIdRoute
    }
    '/operacoes/clientes/$id/historico': {
      id: '/operacoes/clientes/$id/historico'
      path: '/historico'
      fullPath: '/operacoes/clientes/$id/historico'
      preLoaderRoute: typeof OperacoesClientesIdHistoricoRouteImport
      parentRoute: typeof OperacoesClientesIdRoute
    }
    '/operacoes/clientes/$id/financeiro': {
      id: '/operacoes/clientes/$id/financeiro'
      path: '/financeiro'
      fullPath: '/operacoes/clientes/$id/financeiro'
      preLoaderRoute: typeof OperacoesClientesIdFinanceiroRouteImport
      parentRoute: typeof OperacoesClientesIdRoute
    }
    '/operacoes/clientes/$id/documentos': {
      id: '/operacoes/clientes/$id/documentos'
      path: '/documentos'
      fullPath: '/operacoes/clientes/$id/documentos'
      preLoaderRoute: typeof OperacoesClientesIdDocumentosRouteImport
      parentRoute: typeof OperacoesClientesIdRoute
    }
    '/operacoes/clientes/$id/comercial': {
      id: '/operacoes/clientes/$id/comercial'
      path: '/comercial'
      fullPath: '/operacoes/clientes/$id/comercial'
      preLoaderRoute: typeof OperacoesClientesIdComercialRouteImport
      parentRoute: typeof OperacoesClientesIdRoute
    }
  }
}

interface BriefingsRouteChildren {
  BriefingsIdRoute: typeof BriefingsIdRoute
}

const BriefingsRouteChildren: BriefingsRouteChildren = {
  BriefingsIdRoute: BriefingsIdRoute,
}

const BriefingsRouteWithChildren = BriefingsRoute._addFileChildren(
  BriefingsRouteChildren,
)

interface CatalogoRouteChildren {
  CatalogoIdRoute: typeof CatalogoIdRoute
  CatalogoNovoRoute: typeof CatalogoNovoRoute
}

const CatalogoRouteChildren: CatalogoRouteChildren = {
  CatalogoIdRoute: CatalogoIdRoute,
  CatalogoNovoRoute: CatalogoNovoRoute,
}

const CatalogoRouteWithChildren = CatalogoRoute._addFileChildren(
  CatalogoRouteChildren,
)

interface ContratosRouteChildren {
  ContratosIdRoute: typeof ContratosIdRoute
}

const ContratosRouteChildren: ContratosRouteChildren = {
  ContratosIdRoute: ContratosIdRoute,
}

const ContratosRouteWithChildren = ContratosRoute._addFileChildren(
  ContratosRouteChildren,
)

interface PropostasRouteChildren {
  PropostasIdRoute: typeof PropostasIdRoute
}

const PropostasRouteChildren: PropostasRouteChildren = {
  PropostasIdRoute: PropostasIdRoute,
}

const PropostasRouteWithChildren = PropostasRoute._addFileChildren(
  PropostasRouteChildren,
)

interface OperacoesClientesIdRouteChildren {
  OperacoesClientesIdComercialRoute: typeof OperacoesClientesIdComercialRoute
  OperacoesClientesIdDocumentosRoute: typeof OperacoesClientesIdDocumentosRoute
  OperacoesClientesIdFinanceiroRoute: typeof OperacoesClientesIdFinanceiroRoute
  OperacoesClientesIdHistoricoRoute: typeof OperacoesClientesIdHistoricoRoute
  OperacoesClientesIdOperacoesRoute: typeof OperacoesClientesIdOperacoesRoute
  OperacoesClientesIdIndexRoute: typeof OperacoesClientesIdIndexRoute
}

const OperacoesClientesIdRouteChildren: OperacoesClientesIdRouteChildren = {
  OperacoesClientesIdComercialRoute: OperacoesClientesIdComercialRoute,
  OperacoesClientesIdDocumentosRoute: OperacoesClientesIdDocumentosRoute,
  OperacoesClientesIdFinanceiroRoute: OperacoesClientesIdFinanceiroRoute,
  OperacoesClientesIdHistoricoRoute: OperacoesClientesIdHistoricoRoute,
  OperacoesClientesIdOperacoesRoute: OperacoesClientesIdOperacoesRoute,
  OperacoesClientesIdIndexRoute: OperacoesClientesIdIndexRoute,
}

const OperacoesClientesIdRouteWithChildren =
  OperacoesClientesIdRoute._addFileChildren(OperacoesClientesIdRouteChildren)

interface OperacoesClientesRouteChildren {
  OperacoesClientesIdRoute: typeof OperacoesClientesIdRouteWithChildren
}

const OperacoesClientesRouteChildren: OperacoesClientesRouteChildren = {
  OperacoesClientesIdRoute: OperacoesClientesIdRouteWithChildren,
}

const OperacoesClientesRouteWithChildren =
  OperacoesClientesRoute._addFileChildren(OperacoesClientesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiRoute: BiRoute,
  BriefingsRoute: BriefingsRouteWithChildren,
  CadenciaRoute: CadenciaRoute,
  CatalogoRoute: CatalogoRouteWithChildren,
  ContratosRoute: ContratosRouteWithChildren,
  CrmRoute: CrmRoute,
  DashboardRoute: DashboardRoute,
  KickoffRoute: KickoffRoute,
  LoginRoute: LoginRoute,
  MetasRoute: MetasRoute,
  MetasObjetivosRoute: MetasObjetivosRoute,
  PropostasRoute: PropostasRouteWithChildren,
  ProspeccaoRoute: ProspeccaoRoute,
  TarefasRoute: TarefasRoute,
  BriefingTokenRoute: BriefingTokenRoute,
  OperacoesAgendaRoute: OperacoesAgendaRoute,
  OperacoesCampanhasRoute: OperacoesCampanhasRoute,
  OperacoesClientesRoute: OperacoesClientesRouteWithChildren,
  OperacoesCredenciaisRoute: OperacoesCredenciaisRoute,
  OperacoesDashboardRoute: OperacoesDashboardRoute,
  OperacoesFinanceiroRoute: OperacoesFinanceiroRoute,
  OperacoesImplantacaoRoute: OperacoesImplantacaoRoute,
  OperacoesKanbanRoute: OperacoesKanbanRoute,
  OperacoesOnboardingRoute: OperacoesOnboardingRoute,
  OperacoesRelacionamentoRoute: OperacoesRelacionamentoRoute,
  OperacoesRelatoriosRoute: OperacoesRelatoriosRoute,
  OperacoesRenovacoesRoute: OperacoesRenovacoesRoute,
  OperacoesTrafegoRoute: OperacoesTrafegoRoute,
  PropostaTokenRoute: PropostaTokenRoute,
  OperacoesIndexRoute: OperacoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
