/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as ProspeccaoRouteImport } from './routes/prospeccao'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as BriefingsRouteImport } from './routes/briefings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BriefingsIdRouteImport } from './routes/briefings.$id'
import { Route as BriefingTokenRouteImport } from './routes/briefing.$token'

const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspeccaoRoute = ProspeccaoRouteImport.update({
  id: '/prospeccao',
  path: '/prospeccao',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingsRoute = BriefingsRouteImport.update({
  id: '/briefings',
  path: '/briefings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingsIdRoute = BriefingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BriefingsRoute,
} as any)
const BriefingTokenRoute = BriefingTokenRouteImport.update({
  id: '/briefing/$token',
  path: '/briefing/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/briefings': typeof BriefingsRouteWithChildren
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/prospeccao': typeof ProspeccaoRoute
  '/tarefas': typeof TarefasRoute
  '/briefing/$token': typeof BriefingTokenRoute
  '/briefings/$id': typeof BriefingsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/briefings': typeof BriefingsRouteWithChildren
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/prospeccao': typeof ProspeccaoRoute
  '/tarefas': typeof TarefasRoute
  '/briefing/$token': typeof BriefingTokenRoute
  '/briefings/$id': typeof BriefingsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/briefings': typeof BriefingsRouteWithChildren
  '/crm': typeof CrmRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/prospeccao': typeof ProspeccaoRoute
  '/tarefas': typeof TarefasRoute
  '/briefing/$token': typeof BriefingTokenRoute
  '/briefings/$id': typeof BriefingsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/briefings'
    | '/crm'
    | '/dashboard'
    | '/login'
    | '/metas'
    | '/prospeccao'
    | '/tarefas'
    | '/briefing/$token'
    | '/briefings/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/briefings'
    | '/crm'
    | '/dashboard'
    | '/login'
    | '/metas'
    | '/prospeccao'
    | '/tarefas'
    | '/briefing/$token'
    | '/briefings/$id'
  id:
    | '__root__'
    | '/'
    | '/briefings'
    | '/crm'
    | '/dashboard'
    | '/login'
    | '/metas'
    | '/prospeccao'
    | '/tarefas'
    | '/briefing/$token'
    | '/briefings/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BriefingsRoute: typeof BriefingsRouteWithChildren
  CrmRoute: typeof CrmRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MetasRoute: typeof MetasRoute
  ProspeccaoRoute: typeof ProspeccaoRoute
  TarefasRoute: typeof TarefasRoute
  BriefingTokenRoute: typeof BriefingTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospeccao': {
      id: '/prospeccao'
      path: '/prospeccao'
      fullPath: '/prospeccao'
      preLoaderRoute: typeof ProspeccaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefings': {
      id: '/briefings'
      path: '/briefings'
      fullPath: '/briefings'
      preLoaderRoute: typeof BriefingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefings/$id': {
      id: '/briefings/$id'
      path: '/$id'
      fullPath: '/briefings/$id'
      preLoaderRoute: typeof BriefingsIdRouteImport
      parentRoute: typeof BriefingsRoute
    }
    '/briefing/$token': {
      id: '/briefing/$token'
      path: '/briefing/$token'
      fullPath: '/briefing/$token'
      preLoaderRoute: typeof BriefingTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BriefingsRouteChildren {
  BriefingsIdRoute: typeof BriefingsIdRoute
}

const BriefingsRouteChildren: BriefingsRouteChildren = {
  BriefingsIdRoute: BriefingsIdRoute,
}

const BriefingsRouteWithChildren = BriefingsRoute._addFileChildren(
  BriefingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BriefingsRoute: BriefingsRouteWithChildren,
  CrmRoute: CrmRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MetasRoute: MetasRoute,
  ProspeccaoRoute: ProspeccaoRoute,
  TarefasRoute: TarefasRoute,
  BriefingTokenRoute: BriefingTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
